services:
  postgres:
    image: postgres:16
    container_name: recipe-app-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  hasura:
    image: hasura/graphql-engine:v2.48.0
    container_name: recipe-app-hasura-instance
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret@postgres:5432/userapp
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"my-secret-key-my-secret-key-my-secret-key-my-secret-key"}'
      HASURA_GRAPHQL_ADMIN_SECRET: my-admin-secret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: recipe-app-go-client
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/userapp
      HASURA_GRAPHQL_JWT_SECRET: "my-secret-key-my-secret-key-my-secret-key-my-secret-key"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health_check"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: recipe-app-minio-instance
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: on-failure
volumes:
  postgres_data:
  minio_data:
