services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  hasura:
    image: hasura/graphql-engine:v2.48.0
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret@postgres:5432/userapp
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"my-secret-key-my-secret-key-my-secret-key-my-secret-key"}'
      HASURA_GRAPHQL_ADMIN_SECRET: my-admin-secret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/userapp
      HASURA_GRAPHQL_JWT_SECRET: "my-secret-key-my-secret-key-my-secret-key-my-secret-key"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
volumes:
  postgres_data:
